p increment_string("foo")#, "foo1")
p increment_string("foobar001")#, "foobar002")
p increment_string("foobar1")#, "foobar2")
p increment_string("foobar00")#, "foobar01")
p increment_string("foobar99")#, "foobar100")
p increment_string("")#, "1")